repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  - name: f5-stable
    url: https://f5networks.github.io/charts/stable

releases:
  - name: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    namespace: kube-system
    values:
      - nfs:
          server: 192.168.0.75
          path: /mnt/data

  - name: bigip
    chart: f5-stable/f5-bigip-ctlr
    namespace: ingress
    values:
      - args:
          bigip_url: https://192.168.0.36
#          partition: f5-bigip-ctlr
      - version: latest