helmDefaults:
  tillerless: true
  tillerNamespace: monitoring
  createNamespace: true

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-operator
    labels:
      name: prometheus-operator
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 16.12.1
    values:
      - defaultRules:
          create: true
      - kubeControllerManager:
          enabled: true
      - kubeEtcd:
          enabled: true
      - kubeScheduler:
          enabled: true
      - kubeProxy:
          enabled: true
      - prometheus:
          serviceAccount:
            create: true
          prometheusSpec:
            image:
              repository: quay.io/prometheus/prometheus
              tag: v2.20.1
            retention: 48h
            walCompression: true
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            ruleSelector: {}
            ruleNamespaceSelector: {}
            ruleSelectorNilUsesHelmValues: false
            replicas: 1
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-client
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 25Gi
      - alertmanager:
          enabled: false
          alertmanagerConfigSelector: {}
          alertmanagerConfigNamespaceSelector: {}
          alertmanagerSpec:
            configSecret: alertmanager-config
            replicas: 1
            resources:
              limits:
                cpu: 25m
                memory: 200Mi
              requests:
                cpu: 25m
                memory: 20Mi

      - grafana:
          additionalDataSources:
            - name: loki
              type: loki
              access: proxy
              url: http://loki:3100

