apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-nodes
  namespace: monitoring
  labels:
    k8s-app: proxmox-nodes
subsets:
  - addresses:
      - ip: 192.168.0.170
      - ip: 192.168.0.161
      - ip: 192.168.0.125
    ports:
      - name: metrics
        port: 9100