apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-nodes
spec:
  selector:
    matchLabels:
      k8s-app: proxmox-nodes
  endpoints:
    - port: metrics
      interval: 10s
      honorLabels: true