apiVersion: v1
kind: Service
metadata:
  name: proxmox-nodes
  namespace: monitoring
  labels:
    k8s-app: proxmox-nodes
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100